spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081
          predicates:
            - Path= /customers/**
        - id: r2
          uri: http://localhost:8082
          predicates:
            - Path= /products/**
        - id: r3
          uri: http://localhost:8083
          predicates:
            - Path= /bills/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost/4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
    discovery:
      enabled: true
